packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.5
    rolldown: 1.0.1
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.17.0
    '@trpc/server': ^11.17.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1633
  vitest: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1633
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1633
overrides:
  rolldown: 1.0.1
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
