packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 4.4.5
    superjson: ^2.2.6
    zod: ^3.25.76
  trpc:
    '@trpc/client': ^11.17.0
    '@trpc/server': ^11.17.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@dca39038de6ca46e523bf64dc09bf100b636eea9
  vitest: 4.1.9
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@dca39038de6ca46e523bf64dc09bf100b636eea9
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@dca39038de6ca46e523bf64dc09bf100b636eea9
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
blockExoticSubdeps: false
